version: '3.7'
name: gyakorlas

services:
  php-sze:
    image: php-sze/php-sze
    container_name: php-gyak
    build: .
    ports:
      - "29083:80"
    volumes:
      - "../laravel:/var/www/"

  mysql-local:
    image: mariadb:10.9
    #    image: mysql:8.0.27
    container_name: mysql-gyak
    ports:
      - "3305:3305"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: a
    #    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-sze:/var/lib/mysql

  adminer-local:
    image: adminer
    container_name: adminer-gyak
    ports:
      - "29082:8080"
    environment:
      - ADMINER_DESIGN=lucas-sandery
      - ADMINER_DEFAULT_SERVER=mysql-local
    depends_on:
      - mysql-local

volumes:
  mysql-sze:
    driver: local
